### ISSUE TITLE
(Tutorial) Arduino y la Web 2.0

### ISSUE THREAD

**Issue by chepecarlos** [alswnet/NocheProgramacion#22]
Conferencia de como funciona la web 2.0 con Arduino

**Comment by chepecarlos** [comment]
@IngJuanZD editor el video

**Comment by chepecarlos** [comment]
@chepecarlos renderizara el video y lo subira a youtube

**Comment by IngJuanZD** [comment]
El video ya está publicado en Youtube https://youtu.be/7KQe_NQ4O8Y

**Comment by chepecarlos** [comment]
Gracias amigo :)
